### PR TITLE
feat(cache): add `get_all` method

### PR DESCRIPTION
**Pull request by orhun**
This PR adds a new method called `get_all` for retrieving all the CVEs available in the database.

I needed this for the application that I'm building and couldn't find an alternative way of achieving it. Also I think it's good to have it anyways!

### CODE REVIEW

**Comment by orhun** [comment]
Hey @travispaul can you take a look at this soon? 😊

**Review by travispaul — APPROVED** [review]

**Comment by travispaul** [comment]
@orhun LGTM, thanks!

**Comment by orhun** [comment]
Thank you! Is it possible to get a new release soon? I can submit a PR for updating the dependencies if you want.

**Comment by travispaul** [comment]
@orhun If you can update the dependencies please do and I'll push an updated version. Thanks!

**Comment by orhun** [comment]
Sorry for the late reply :/ It looks like you beat me to it!

**Comment by travispaul** [comment]
@orhun no worries, had a bit of spare time this morning :)

**Comment by orhun** [comment]
Can you also publish on crates.io? 😊

**Comment by orhun** [comment]
Thanks! Btw what do you think about my TUI comment here: https://github.com/travispaul/nvd_cve/pull/11#issuecomment-2072990547

Do you think anything else can be added? Currently it only supports browsing for CVEs.

**Pull request merged**
